name: soniamalpeso
favicon: null
layout_spectrum: 0.10515
typography_spectrum: 0.0896610482595861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfefc'
    - '#0c0a0c'
    - '#444644'
    - '#747274'
    - '#a4a6a4'
  brandStrength: 0.1875
  lightness: 0.662297192029655
  saturation: 0.3465496217831969
  rhythmicContrast: 0.5
purpose: []
